[package]
name = "sei-mcp-server-rs"
version = "0.1.0"
edition = "2024"


[dependencies]

reqwest = { version = "0.12", features = ["json"] }

axum = "0.7"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15"
bip39 = "2.0"
ethers-core = { version = "2.0" }
hex = "0.4"
tokio-util = "0.7"
thiserror = "1.0"
rand = "0.8"
chrono = { version = "0.4.41", features = ["serde"] }
futures = "0.3"
